### ISSUE TITLE
[PE-D][Tester B] addfav documentation states that favourited indices are invalid but program returns a warning

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T16-3/tp#123]
![image.png](https://raw.githubusercontent.com/miffi/ped/main/files/93cc300d-b8f9-4f92-80b4-0e0801cf64d0.png)

![image.png](https://raw.githubusercontent.com/miffi/ped/main/files/f1ae60ff-a081-4047-a930-8a3fe23fe224.png)

The documentation gave me the impression that the invalid values would make the program reject the command, but the command runs and shows a warning instead.

The use of the word "invalid" in the docs doesn't really make sense in this case because it's still a valid input. Maybe write a short blurb about the warning instead?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: miffi/ped#8

**Comment by sun-ruiheng** [comment]
Resolved — removed this line and the similar one for `removefav` in the UG.
