### ISSUE TITLE
[PE-D][Tester D] Redundant Repetition of Rule

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T16-3/tp#93]
Repetition of the "multiple search fields will be treated as a logical AND" rule: once in general format, once in search guidelines.

![image.png](https://raw.githubusercontent.com/vannykin/ped/main/files/9ee0fd80-78f1-4566-9911-353aa5b0ea57.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: vannykin/ped#7

**Comment by guanquann** [comment]
Duplicate
