### ISSUE TITLE
[PE-D][Tester D] Inconsistent Use of Terms

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T16-3/tp#99]
Very inconsistent use of the words 'contact', 'person' and 'supplier' throughout the UG.

This makes the user experience quite confusing.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: vannykin/ped#10

**Comment by sun-ruiheng** [comment]
Changed all to 'contact' to standardize.
